---
- hosts: all

  vars:
    applications:
      - firefox
      - google-chrome
      - gpgtools
      - limechat
      - sequel-pro
      - sonos
      - the-unarchiver
      - tunnelblick
      - vagrant
      - virtualbox
      - atom
      - coteditor
    application_dir: /Applications
    brews:
      - ack
      - chromedriver
      - docker
      - hub
      - ios-webkit-debug-proxy
      - rsync
      - zsh
      - rbenv
      - ruby-build
      - nodebrew
      - go
      - jq
      - tig
      - tmux
      - coreutils
      - findutils
    caskroom_dir: /usr/local/caskroom
#    dotfiles_dir: /Users/udzura/Code/dotfiles
    email: udzura@pepabo.com
    github_username: udzura
    home_dir: /Users/udzura
    name: Uchio KONDO
    zsh_path: /usr/local/bin/zsh

  tasks:
    - include: tasks/homebrew.yml tags=homebrew
    - include: tasks/zsh.yml tags=zsh
    # - include: tasks/dotfiles.yml tags=dotfiles
