---
- hosts: all

  vars:
    applications:
      - firefox
      - google-chrome
      - gpgtools
      - limechat
      - sequel-pro
      - the-unarchiver
      - tunnelblick
      - vagrant
      - virtualbox
      - atom
      - coteditor
      - licecap
      - skype
      - thunderbird
      - dropbox
      - unity-web-player
      - flash-player
    application_dir: /Applications
    brews:
      - ack
      - chromedriver
      - docker
      - boot2docker
      - hub
      - ios-webkit-debug-proxy
      - rsync
      - zsh
      - openssl
      - libyaml
      - readline
      - nkf
      - rbenv
      - ruby-build
      - nodebrew
      - go
      - jq
      - tig
      - tmux
      - weechat
      - coreutils
      - findutils
      - gcc
      - mysql
      - mysql51
    caskroom_dir: /usr/local/caskroom
#    dotfiles_dir: /Users/udzura/Code/dotfiles
    email: '{{ email }}'
    github_username: '{{ github_username }}'
    go_applications:
      - github.com/motemen/ghq
      - github.com/peco/peco/cmd/peco
      - github.com/monochromegane/the_platinum_searcher/cmd/pt
    home_dir: '{{ home }}'
    name: '{{ name }}'
    zsh_path: /usr/local/bin/zsh

  tasks:
    - include: tasks/homebrew.yml tags=homebrew
    - include: tasks/zsh.yml tags=zsh
    - include: tasks/emacs.yml tags=emacs
    - include: tasks/golibs.yml tags=golibs
    - include: tasks/defaults.yml tags=defaults
    # - include: tasks/dotfiles.yml tags=dotfiles
